GET http://localhost:5000/users

###

GET http://localhost:5000/articles/

###
POST http://localhost:5000/user/
Content-Type: application/json

{
    "name": "John",
    "email": "John.Doe@gmail.com",
    "password": "123456"
    }

###

POST http://localhost:5000/articles
Content-Type: application/json
[
    {
        "Name": "Article 1",
        "Description": "Article 1 body",
        "Price": 15.99,
        "Image": "http://www.google.com/image.png"
    },
    {
        "Name": "Article 2",
        "Description": "Article 2 body",
        "Price": 15.99,
        "Image": "http://www.google.com/image.png"
    }
]
